// File generated by FlutterFire CLI — keep this as the single place to paste
// the public web SDK config. Filling apiKey / appId / projectId (and the
// other web fields) is a one-file change.
//
// TODO: paste the Firebase console web app values (Project settings → Your
// apps → Web). Do not invent a production project id. The apiKey in this file
// is the public client SDK key, not a secret. Never commit a service-account
// JSON.
//
// After pasting config:
// 1. Enable Google sign-in in Authentication → Sign-in method.
// 2. Add authorized domain `michaelady.github.io` (Authentication → Settings).
// 3. Deploy `firestore.rules` (`firebase deploy --only firestore:rules`).
// 4. Create a Firestore database (Spark / native mode is enough).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

abstract final class DefaultFirebaseOptions {
  /// True once [web] has a real apiKey, appId, and projectId.
  static bool get isConfigured {
    final options = web;
    return options.apiKey.isNotEmpty &&
        options.appId.isNotEmpty &&
        options.projectId.isNotEmpty;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Native targets compile against the public web SDK config until
    // platform-specific FlutterFire apps are added. Google sign-in on web
    // (GitHub Pages) is the supported success path for this release.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.fuchsia:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    authDomain: '',
    storageBucket: '',
  );
}
